/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\maximos\repos\GBDevCourse\tutorials\11_motion_in_map\map\map_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapWidth 20
#define mapHeight 18
#define mapBank 0

extern unsigned char map[];

/* End of MAP.H */
