#Emulicious settings file
#Tue Jun 02 13:51:10 EEST 2026
Recent6=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/13_grab_and_use_item/build/game.gb
Recent5=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/14_bandit_chase/build/game.gb
CodeFontSize=13
Recent4=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/14_bandit_chase/build/game.gb
Recent3=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/14_bandit_chase/build/game.gb
Recent9=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/13_grab_and_use_item/build/game.gb
Recent8=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/13_grab_and_use_item/build/game.gb
Recent7=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/13_grab_and_use_item/build/game.gb
WindowEmuliciousY=1050
Scale=5.75
Update=2
Recent2=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/14_bandit_chase/build/game.gb
Recent1=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/14_bandit_chase/build/game.gb
WindowEmuliciousX=804
Recent0=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/14_bandit_chase/build/game.gb
FontSize=13
AudioSync=false
WindowEmuliciousHeight=948
WindowEmuliciousWidth=996
