#Emulicious settings file
#Tue May 26 11:37:16 EEST 2026
Recent6=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/09_sprite_motion_anim/build/game.gb
Recent5=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/09_sprite_motion_anim/build/game.gb
CodeFontSize=13
Recent4=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/10_sprite_motion_struct/build/game.gb
Recent3=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/10_sprite_motion_struct/build/game.gb
Recent9=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/09_sprite_motion_anim/build/game.gb
Recent8=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/09_sprite_motion_anim/build/game.gb
Recent7=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/09_sprite_motion_anim/build/game.gb
WindowEmuliciousY=1071
Scale=4.75
Update=2
Recent2=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/10_sprite_motion_struct/build/game.gb
Recent1=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/10_sprite_motion_struct/build/game.gb
WindowEmuliciousX=674
Recent0=/mnt/c/Users/monog/repos/GBDevCourse/tutorials/10_sprite_motion_struct/build/game.gb
FontSize=13
AudioSync=false
WindowEmuliciousHeight=804
WindowEmuliciousWidth=836
