#Emulicious settings file
#Wed May 27 22:30:00 EEST 2026
WindowEmuliciousWidth=760
FontSize=13
AudioSync=false
Scale=4.75
Recent9=/home/maximos/repos/GBDevCourse/tutorials/12_motion_in_map_constraint/build/game.gb
Update=2
WindowEmuliciousY=1455
Recent8=/home/maximos/repos/GBDevCourse/tutorials/12_motion_in_map_constraint/build/game.gb
WindowEmuliciousX=674
Recent7=/home/maximos/repos/GBDevCourse/tutorials/12_motion_in_map_constraint/build/game.gb
Recent6=/home/maximos/repos/GBDevCourse/tutorials/12_motion_in_map_constraint/build/game.gb
Recent5=/home/maximos/repos/GBDevCourse/tutorials/12_motion_in_map_constraint/build/game.gb
Recent4=/home/maximos/repos/GBDevCourse/tutorials/12_motion_in_map_constraint/build/game.gb
Recent3=/home/maximos/repos/GBDevCourse/tutorials/12_motion_in_map_constraint/build/game.gb
Recent2=/home/maximos/repos/GBDevCourse/tutorials/12_motion_in_map_constraint/build/game.gb
Recent1=/home/maximos/repos/GBDevCourse/tutorials/12_motion_in_map_constraint/build/game.gb
Recent0=/home/maximos/repos/GBDevCourse/tutorials/12_motion_in_map_constraint/build/game.gb
CodeFontSize=13
WindowEmuliciousHeight=705
