/*

 BANDIT_SPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char bandit_sprite[] =
{
  0xC3,0xC3,0xFF,0x81,0x7E,0x66,0x5A,0x24,
  0x7E,0x00,0x7E,0x7E,0x3C,0x66,0x00,0x42
};

/* End of BANDIT_SPRITE.C */
