/*

 KEY_SPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char key_sprite[] =
{
  0x00,0x00,0x00,0x00,0x60,0x60,0x9F,0x9F,
  0x95,0x95,0x60,0x60,0x00,0x00,0x00,0x00
};

/* End of KEY_SPRITE.C */
