/*

 KILLER_RABBIT_SPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char killer_rabbit_sprite[] =
{
  0x00,0xC3,0x18,0x66,0x3C,0x24,0x3C,0x66,
  0x18,0x3C,0x18,0x66,0xFF,0x18,0x7E,0x00
};

/* End of KILLER_RABBIT_SPRITE.C */
